Import('env')

sources = ['qreoroot.F','fofclibPlus.c','qufap.F','unixqufap.F']


progNode = env.Program('qreou',
                       source = sources,
                       CPPPATH = [env.installLocalInc],
                       LIBPATH = [env.installLocalLib],
                       LIBS    = ['qreo','dap','s2'])

env.Install(env.installLocalBin,progNode)
