Import('env')

sources = ['xcedcio.c','fofclib.c','qreo1.F','qreo2.F','qreo3.F','unixqreo.F','foflib.F','unixflib.F']

libNode = env.Library('qreo',source = sources,CPPPATH = [env.installLocalInc]);

env.Install(env.installLocalLib,libNode);

