Import('env')

sources = ['xcedcio.c','fofclib.c','qreo1.F','qreo2.F','qreo3.F','unixqreo.F','foflib.F','unixflib.F']

env.AppendUnique(CPPPATH = [env.installLocalInc])

libNode = env.Library('qreo',source = sources);

env.Install(env.installLocalLib,libNode);

