Import('env')

sources = ['qreoroot.F']


env.AppendUnique(CPPDEFINES = ['UNIX','LITTLENDIAN'])
env.AppendUnique(LIBPATH    = [env.installLocalLib])
env.AppendUnique(CPPPATH    = [env.installLocalInc])
env.PrependUnique(LIBS       = ['qreo','dap','s2'])

progNode = env.Program('qreod', source = sources)

env.Install(env.installLocalBin,progNode)
