Import('env')

sources = Glob('*.c')

env.AppendUnique(CPPDEFINES = ['UNIX','LITTLENDIAN'])
env.AppendUnique(LIBS       = ['m','ncurses'])
env.AppendUnique(CPPPATH    = [env.installLocalInc])

libNode = env.Library('s2',source = sources)

env.Install(env.installLocalLib,libNode);

